# Generated by Django 4.1.7 on 2023-04-27 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_alter_discussion_complain_alter_discussion_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='complain',
            field=models.ManyToManyField(blank=True, null=True, related_name='complain_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislike_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
