# Generated by Django 4.1.7 on 2023-04-28 11:11

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_quizquestion_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResultText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.tests')),
            ],
            options={
                'verbose_name': 'Quiz Result Text',
                'verbose_name_plural': 'Quiz Result Texts',
                'db_table': 'QuizResultText',
            },
        ),
    ]
